name: news
description: A Flutter Repository( ApiProvider & DbProvider & BLoC ) project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  equatable: ^2.0.5
  http: ^1.1.0
  ansicolor: ^2.0.1

  ## old rxdart( 0.23.0 이전 ) : Stream 대신 Observable 사용
  ## rxdart: ^0.22.6
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true
  assets:
    - assets/images/loading.gif  